### ISSUE TITLE
Implement `div_euc` for vector types

### ISSUE THREAD

**Issue by zesterer** [yoanlcq/vek#11]

**Comment by yoanlcq** [comment]
The issues I see : 
- `div_euc` and `mod_euc` in the std are nightly only. Do we use the std with a feature gate, or do we roll our own?
- We need a trait that provides `div_euc` and `mod_euc`. To me, the best way to go would be to add it to the `Num` trait of `num_traits` (or add a new trait there or whatever; in any case that may be controversial). An alternative is just to roll our own trait and implement it for primitive types.

As an aside, this kind of thing immediately made me think about the `map` method. We might actually want some kind of `map2` method which would allow anyone to write e.g `let res = a.map2(b, |(x, y)| x.div_euc(y));` (which is admittedly a bit verbose...)

**Comment by yoanlcq** [comment]
I wouldn't mind some kind of `EucOps` trait in `vek::ops`; however, this "feels" very much like an `std` feature. `Clamp`, `Lerp` and friends were OK because they're not in `std`, and other "very-close-to-standard" traits are provided by `num-traits`.

My point is, I prefer avoiding to add such traits to `vek`; If anything, it would rather belong in `num-traits`; and then we could implement it for vectors `where T: EucOps`.

**Comment by zesterer** [comment]
`div_euclid` and `rem_euclid` are now stable.

**Comment by yoanlcq** [comment]
Yup, I would wait to see how this will be handled in `num-traits`.

**Comment by SparrowLii** [comment]
I have submitted the [pr](https://github.com/rust-num/num-traits/pull/195) in num-trait. Could I ask what this operation does in vek ?( just curious.)

**Comment by zesterer** [comment]
@SparrowLii It doesn't exist in `vek` yet. I assumed it would just apply `div/rem_euclid` element-wise for vectors in much the same way as other arithmetic operations.

**Comment by Patiga** [comment]
Fixed by 2e10920c397ee4c4d3f7cb0611b9e072700e92cf via #86

**Comment by yoanlcq** [comment]
Thanks @Patiga !
