### ISSUE TITLE
Const constructor

### ISSUE THREAD

**Issue by xMAC94x** [yoanlcq/vek#12]
Hi,
i want to have const Vec3, is this possible ?

e.g.
```rust
const ENTITY_MIDDLE_OFFSET: Vec3<f32> = Vec3::new(0.0, 0.0, 0.9);
```

best regards,
xMAC94x

**Comment by yoanlcq** [comment]
Ok so it works perfectly under nightly. However I also want to support the stable channel, which does require `#![feature(const_fn)]`; and there I'm not sure myself of how I want to approach this.

So far my stance has been "either you're on nightly, in which case you opt-in for all the cool unstable features, OR you're on stable in which case you want to take absolutely zero risk.", or put another way : you're either 100% nightly or 100% stable but there's no middle ground.

I _could_ just add `#[feature(const_fn)]` and it would probably be fine, but I'm worried about stuff like Internal Compiler Errors, especially since there's SIMD stuff in this crate (which as far as I remember is unstable too. I remember having to work around ICEs with reduce operations on `bool` vectors, for instance).  
I suspect I'm being paranoid here, but I would hate for people to come back at me saying `I can't call VecX::new() anymore on stable in [insert very specific context here]`.

Another option is to provide a `const_fn` cargo feature to which people could opt-in to; but in this case we'll end up with code like this (pseudo-Rust) : 

```rust
impl<T> Vec3<T> {
    #[cfg(not(const_fn))]
    pub fn new(...) { ... }
    #[cfg(const_fn)]
    pub const fn new(...) { ... }
}
```
Imagine this for all of `vek`'s types, multiplied by the number of `const-able` functions such as `zero()` and `one()`; This looks like too much trouble for what it's worth.

I, too, would like most functions to be `const`; this would be very practical and cool-looking. But I'm not seeing any satisfactory solutions at the moment (but I'm open to suggestions of course! :) ).  
This mostly depends on how important this feature is to you!

_Side notes: I've always worked around the `const fn` limitation either via explicit struct initialization, or by using plain old functions. Or often, things I thought should be "const" don't actually need to be, thus offering more run-time flexibility. But I agree that's not an excuse for the underlying problem._

**Comment by SrTobi** [comment]
I really would like to see this feature.

Why not wrap every function in some kind of macro that can either respect the feature flag or the config flag or both. I tried the following code and it works fine:

````rust
macro_rules!  make_const {
    (fn $name:ident() -> $retty:ty $body:block) => {
        #[cfg(not(feature = "const_functions"))]
        fn $name() -> $retty $body

        #[cfg(feature = "const_functions")]
        const fn $name() -> $retty $body
    };
}

make_const!(
    fn some_deterministic_fn() -> i32 { 8 }
);

// the following does not work when the flag "const_functions" is set 
const X: i32 = some_deterministic_fn();

fn main() {
    println!("{}", X);
}
````

**Comment by yoanlcq** [comment]
I could see this macro-based approach work, however to make it compatible with existing signatures such as :

```rust
/// doc comments, blah blah blah
pub fn map2<D,F,S>(self, other: $Vec<S>, mut f: F) -> $Vec<D> where F: FnMut(T, S) -> D {
    /* insert function body here */
}
```

... would require turning it into quite the monster. I feel it's possible, just not very pretty.  
In any case we could make it so it accepts multiple functions instead of just one, such that there's only a need to say `impl Foo { make_const!{ ... all functions here ... } }`, instead of once per function.

My concern is that we're really working around what's supposed to be a language feature. Taking a step back, my previous statement about `#[feature(const_fn)]` and internal compiler errors is probably unwarranted, since `const_fn` has had plenty of time to mature, and after all, ICEs are bugs, that _should_ be reported.  
What I could do is simply add `#[feature(const_fn)]` to my local copy of vek and compiling my other crates against it. If there are ICEs, then I'll consider the macro-based approach, but if there aren't, then it's very likely that everything will be fine for everyone.  
I'll try this evening since I won't be able to do that at work.

I also would very much like to see how other "successful" crates approach this; maybe `nalgebra`, `cgmath` and `num`, but not only math-related crates.

**Comment by zesterer** [comment]
I suspect that the status of this has changed given the recent stabilisation activity around `const fn`.

**Comment by xMAC94x** [comment]
@yoanlcq  did you already fix that with https://github.com/yoanlcq/vek/commit/c81fda520275c3e994ac67d824394894b1d57369 ?
So this can be closed right ?

**Comment by yoanlcq** [comment]
Hmm I guess I did... And it does fix what you initially asked for.

I guess I wanted to leave this issue opened as a reminder for myself to try to extend it to other functions, but since there has been no progress on it we might as well close it. It's always possible to re-open later if desired.

Thanks.
