### ISSUE TITLE
Add conversions for `mint` types?

### ISSUE THREAD

**Issue by icefoxen** [yoanlcq/vek#18]
The `mint` crate is basically an indirection layer for basic vector math types.  Its goal is to make it easier for people to write API's that can accept math types from different libraries.  I've used it in the `ggez` library and it works quite well; instead of a function taking `nalgebra::Point2` and forcing the user to use not only `nalgebra`, but a specific *version* of `nalgebra`, I can have a function take `Into<mint::Point2>`.  `nalgebra`, `cgmath` and a couple other math libraries all have features that provide `Into<mint::Point2>` conversions for their `Point2` types, so you can use whatever math library you want to make games with `ggez` now.

Is this functionality interesting to you at all?  Would you care for a PR?

**Comment by yoanlcq** [comment]
I must confess I knew about `mint` from the beginning and didn't really bother because back then I didn't really see the point : to me, it's normal to choose a single math lib for a project and stick to it. Then, writing helper functions for bridging the gap with other libs usually does not require so much time that it warrants a bunch of dependencies.

But that's only my opinion, and it's less important than freedom for users; so yes, I am interested in this :) I also understand better how useful it is with `ggez` as an example.

A PR would be greatly appreciated if you are so inclined. :)

**Comment by termhn** [comment]
I started on this but to be honest couldn't be bothered to figure out the structure of where the conversions should actually be added for everything given how the macroness is structured in `vek`... however I would appreciate this functionality, as I want to use vek types with `minterpolate`.
