### ISSUE TITLE
In the code: Handedness makes no sense for view/model matrices until someone proves me wrong

### ISSUE THREAD

**Issue by sunjay** [yoanlcq/vek#21]
Could you explain the note in this code?

https://github.com/yoanlcq/vek/blob/c81fda520275c3e994ac67d824394894b1d57369/src/mat.rs#L2245-L2252

Specifically,

> NOTE: Handedness makes no sense for view/model matrices until someone proves me wrong

I'm new to graphics and still wrapping my head around this, so forgive me if I'm completely wrong. I think I ran into an issue caused by handedness today. I had some code that assumes right-handedness and it just did not work with `look_at` because it assumes left-handedness. I do believe handedness matters with `look_at`, but this comment in the code implies differently.

Does handedness actually not matter for `look_at`? Or was there some other reason behind this comment? Would you accept a PR to make those handedness-specific versions of these functions public?

**Comment by yoanlcq** [comment]
Hi,

Very interesting question! :)

Well, my reasoning was that, the only time handedness matters is when coordinates are mapped from your space (LH or RH) to your graphics API's NDC (Normalized Device Coordinates).  
Because `look_at` does not define such a mapping (it's supposedly a "your-space"-to-"your-space" mapping), handedness would not matter.  
To me, it would be like, for instance, basic translation/rotation/scale: They are defined relatively to X, Y or Z, regardless of handedness.

... But the thing I failed to notice was that `look_at`, though such a translation/rotation combination, is not actually defined relatively to absolute axii. Rather, `look_at` is usually called this way : 
```rust
look_at(position, position + forward, up);
```
... and that `forward` vector implies a dependency on handedness, because it changes with it. Oops.

So I was wrong, and should've followed GLM's example. :) What I'm going to do is make `look_at_lh` and `look_at_rh` public, and deprecate `look_at`. If your code "worked" when flipping the `forward` vector (assuming the given example), then that's definitely where your problem is coming from.

Anyways, thanks for reporting this. I very much appreciate it. :)  
My next commit will close this issue, but feel free to leave other comments or reopen if you still have problems.

**Comment by sunjay** [comment]
Thank you for your explanation! Yes, flipping my forward vector did in fact fix the issue, so it's exactly as you described. Could you release a new version so I can start using this right away? Thank you again :)

**Comment by yoanlcq** [comment]
This fix is now published in 0.9.7 :)
