### ISSUE TITLE
Calculate scalar multiple of vector?

### ISSUE THREAD

**Issue by Thomspoon** [yoanlcq/vek#23]
Is it possible to add the Mul trait to floating point values? Is there a workaround in the meantime for VecX? There should be a function like:
```
fn scale<T>(&self, scale: T) -> Self;
```

Unless I'm missing something from the API, I'd have to do something like:
```
Vec3::new(old_vec[0] * x, old_vec[1] * x, old_vec[2] * x);
```

**Comment by Thomspoon** [comment]
Ah, I figured out the trait wanted to multiply by reference, sorry.

**Comment by yoanlcq** [comment]
Hi,

Yeah, that is because of this : 
https://github.com/yoanlcq/vek/blob/c81fda520275c3e994ac67d824394894b1d57369/src/vec.rs#L165-L186

I could not properly explain why commenting the first impl was needed; probably because of the `T: Copy` bound required for copying the scalar value for each vector element. Anyways the compiler complained and I didn't wish to fight it.  
But I'm with you on that one; it should be allowed to multiply the vector by value. It makes more sense, especially for SIMD types...
