### ISSUE TITLE
Add a .join() method to do element-wise joining of vectors

### ISSUE THREAD

**Issue by zesterer** [yoanlcq/vek#32]
```rs
impl<T> Vec2<T> {
    fn join<U>(self, other: Vec2<U>) -> Vec2<(T, U)> {
        Vec2::new((self.x, other.x), (self.y, other.y))
    }
}
```

This is extremely useful as a way to do arbitrary-N mapping. For example:

```rs
let x = ...; // A vector
let lower = ...; // Another vector
let upper = ...; // Another vector

let bounded_x = x
    .join(lower)
    .join(upper)
    .map(|((x, lower), upper)| x.max(lower).min(upper));
```

**Comment by yoanlcq** [comment]
Sorry for the late reply!

I see the point of your example. Interestingly, `a.join(b)` is `a.map2(b, |a, b| (a, b))`; this is a nice property for implementing it with vectors of any length.  

Since it is also equivalent to `a.into_iter().zip(b).collect()`, I'm wondering if we should call it `zip()`, and if other libraries have a `join()` method for similar types (maybe it has a different meaning?).  

In any case it's not that big a deal. I would go with `zip()` for consistency with the standard library (I mean that's more or less what we're doing with `map()`) but it's OK if you prefer `join()`!

**Comment by yoanlcq** [comment]
For instance in the standard library, `join()` is used for the famous "join strings" operations; the only thing that concerns me is that the meaning of `join()` for vectors might not be be obvious, but `zip()` more or less is, and `Iterator` helps because it established a meaning for it.
