### ISSUE TITLE
Add a .reverse() method to swap the elements of a vector into reverse order

### ISSUE THREAD

**Issue by zesterer** [yoanlcq/vek#35]
```rs
let a = Vec3::new(1, 2, 3);
let b = a.reversed();
assert_eq!(b, Vec3::new(3, 2, 1));
```

There are quite a few circumstances for which this feature would be useful. For example, switching between two adjacent coordinate spaces.

**Comment by yoanlcq** [comment]
I don't understand how reversing vectors this way allows to achieve what you claim it does; would you happen to have an example, maybe also giving an idea of how often it is useful?

This looks to me like something that should be a standard operation on arrays or slices, but it would get wordy quite quickly if we were to convert them back into vector values.

Another way to think about it is the "shader" way, where you would just write `let b = a.zyx`. In fact, in an "ideal" world, you could type `a.xy` and this would fix #36 :)

Supporting all swizzling combinations is a combinatorial nightmare, but hopefully (if we go this route) we could support the few "most useful" ones. But still, I don't see how `zyx` could be more useful than, say, `yzx`.  It appears to me that such "swizzling needs" are application-specific, just like coordinates systems.

If we put it another way, if someone comes to me asking for a `xz()` implementation, because they're doing it all the time in their application, should we add it? it's a tough call. If `reverse()` is special for some reason I don't see (it might!), then yeah, let's add it, but let's also watch out for feature creep. :)

**Comment by zesterer** [comment]
This is most useful in the case of `Vec2`: reversing the order of the components is useful when rotating the vector through 90 degrees.

**Comment by yoanlcq** [comment]
I'm about to add it to the library for all vector types; Is it OK for you if I use the "swizzle notation" instead of "reverse" ? This way `Vec2` would have `yx()`, `Vec3` would have `zyx()`, but it's a matter of taste.  
The way I see it, it would be more consistent with the `Vec3::xy()` you requested as well. (`Vec4` would also have `xyz()` as well, same for colors, etc).

**Comment by zesterer** [comment]
That's much better! Thanks!
