### ISSUE TITLE
Outdated/insecure dependencies

### ISSUE THREAD

**Issue by martin-t** [yoanlcq/vek#64]
I checked https://deps.rs/repo/github/yoanlcq/vek and it appears some deps are outdated, one of them marked as insecure.

Updating approx might be a breaking change for crates which depend on approx explicitly in their Cargo.toml to import some of its traits. E.g.: My project uses `vek = "0.12.0"` and `approx = "0.3.2"`, I wanted to update to `approx = "0.4.0"` but can't because I am using `Vec2<f64>::default_epsilon()` from the `approx::AbsDiffEq` trait, which means I need to depend on the same version of vek - IIUC when vek updates, projects doing this will need to update too.

Not sure how many changes are needed in vek as part of the update, I can look into it if you want.

Regarding insecure deps: Have you considered running something like `cargo audit` periodically as part of CI? I see vek is using travis - didn't they drop support for OSS projects? Are you planning to move to something else? I only have experience with GitLab CI but i know GitHub Actions should be able to run periodically (not just on push) using a cron-like schedule.

**Comment by yoanlcq** [comment]
Hi,

Sorry for the late reply. I think updating our dependencies is fine as long as we increase our minor version number. Since we still have a major version 0, any update is allowed to be incompatible with a previous one, so users would have no issue unless they choose to explicitly update their `vek` version dependency on their own. That is, unless I misunderstood how it works...

I'll take a look at this today. Again, I think it's fine if there are some breaking changes here and there, because we would make a new version.

> Have you considered running something like cargo audit periodically as part of CI?

I didn't know about `cargo audit`, but that sounds like a good idea! I'll take a look.

> I see vek is using travis - didn't they drop support for OSS projects? Are you planning to move to something else?

Um, what do you mean? AFAIK Travis is still operating correctly for my projects, and I've never heard that they would drop support for OSS projects as you say, neither could I find any evidence of this... Where have you seen this exactly? I'd be interested in knowing.  
Anyway, until I know for sure, I'm not really planning to move to something else.

**Comment by yoanlcq** [comment]
I closed this in my commit, but I'm keeping an eye on the CI status and will add fixes if needed.

**Comment by yoanlcq** [comment]
By the way, I've learnt just now that Travis CI won't actually shut down support for OSS projects; they will simply shut down `travis-ci.org` today, but this only means that you need to migrate your repos to `travis-ci.com`, possibly using the "Free" pricing plan which works as usual.

I'm enclined to support this change as they'll only have to manage a single domain name and single UI.

**Comment by martin-t** [comment]
> Since we still have a major version 0, any update is allowed to be incompatible with a previous one, so users would have no issue unless they choose to explicitly update their vek version dependency on their own. That is, unless I misunderstood how it works...

To be precise, rust's interpretation of semver is that only increasing the first nonzero number can be a breaking change so for e.g. 0.12.1 -> 0.12.2 is not breaking but 0.12.1 -> 0.13.0 is. This is different from the https://semver.org/ standard which says anything before 1.0 is unstable and any version [can be breaking](https://semver.org/#spec-item-4).

You might wanna use `cargo audit --deny warnings` in CI, not actually sure but e.g. when a crate is unmaintained, it's only a warning, not an error. If you wanna ignore some warnings, you can use `--ignore`. Depends how careful you wanna be.

> Travis CI won't actually shut down support for OSS projects

Interesting - i might have misunderstood then - i only heard what other people were saying ... or travis backed out of it, idk.

Thanks for updating.
