### ISSUE TITLE
Should max and min take different type args?

### ISSUE THREAD

**Issue by xixixao** [yoanlcq/vek#65]
`Vec2::min(2.0, 3.0)` is allowed, but `Vec2::min(2.0, Vec2::new(3.0, 1.0))` doesn't work, is this intentional?

**Comment by yoanlcq** [comment]
I think, since `min` is defined as `fn min<V: Into<Self>>(a: V, b: V)` and we call `.into()` on both arguments anyway, then yeah, we might as well rewrite it as `fn min<U: Into<Self>, V: Into<Self>>(a: U, b: V)` .  
That would support your use case and it's not a breaking change, so I'm all for it!

I'll implement this change ASAP.

**Comment by yoanlcq** [comment]
The fix is available in version 0.13.1 :)
