### ISSUE TITLE
Remove length 3 repr_simd vectors

### ISSUE THREAD

**Issue by calebzulawski** [yoanlcq/vek#66]
In https://github.com/rust-lang/rust/pull/80652 we are removing support for non-power-of-two vector lengths with `#[repr(simd)]` from nightly Rust, and `vek` is one of the crates that will be effected.  Just wanted to give a heads up before we make the change.  If you have any questions feel free to ask!

**Comment by yoanlcq** [comment]
Hi, thanks for letting me know!

Fortunately this will be easy to fix on my side, I'll just make the non-power-of-two vectors in my `repr_simd` modules be actually `#[repr(C)]` instead, so this wouldn't break the API, although this has minor consequences related to alignment and stuff, but I doubt anybody would complain. If they do care, they should be using length 4 vectors instead anyway.

That said, I liked the fact that it "worked" and that the compiler would silently round up the length to the next power of two. Very often I like to use a `Vec3` because it describes my intent exactly, but still have it backed by an SIMD register for efficiency.  
Compared to biting the bullet and using a `Vec4`, this has positive consequences such as : 
- Completely preventing (erroneous) use of the 4th element, since there is no such member in the struct;
- Some operations such as the cross product only make sense for `Vec3`. Of course I could implement these for `Vec4` as well (and I probably will have to), but it was nice to have the type system help me enforce this while backing that with SIMD for me.

I wish it could keep "working" as it did, but I understand that this regression may make life significantly easier for the backend, so let's roll with it!

**Comment by calebzulawski** [comment]
I agree with all of your reasoning and I'll open an issue with `stdsimd` to make sure we get to it eventually.  Unfortunately the cranelift backend does not support unusual vector lengths yet, and we are trying to bring `std::simd` and cranelift simultaneously.  Once cranelift supports it, we can reenable it.  Thanks for the quick fix!
