### ISSUE TITLE
Use `MulAdd` from num-traits

### ISSUE THREAD

**Issue by zakarumych** [yoanlcq/vek#73]
`vek` uses traits from `num-traits` but rolls its own `MulAdd` trait for some reason.
It could be that there was no `MulAdd` in `num-traits` when it was added to `vek`.
Right now this seems confusing.

**Comment by yoanlcq** [comment]
Thanks for bringing this to my attention!

> It could be that there was no MulAdd in num-traits when it was added to vek.

That is true IIRC. When I wrote `vek` I made sure to use `num-traits` extensively, and I would have preferred using num-traits's MulAdd rather than rolling my own.

So I agree and I'd be in favor of using `num-trait`'s `MulAdd`. This is technically a breaking change but I think it'll be fine. I'll try to take some time to look into this soon.

**Comment by zakarumych** [comment]
I think that if `vek` would re-export `MulAdd` it won't be breaking change then.

**Comment by yoanlcq** [comment]
Re-exporting `MulAdd` appeared to do the trick with no issue.

Interestingly enough though, it is still a (slightly) breaking change because now `MulAdd` is not implemented for `std::num::Wrapping<T>`, and regardless of that, the actual operation's implementation may have changed.  
No big deal, it just means I'll update the minor version instead of the patch version, and call it a day.

**Comment by yoanlcq** [comment]
I've published the 0.15.0 version with the fix just now, so I'll close this. Thanks again.
