### ISSUE TITLE
Inclusive ranges are stable now

### ISSUE THREAD

**Issue by CAD97** [yoanlcq/vek#76]
https://github.com/yoanlcq/vek/blob/837cd9bd08f3927dfdbbb8e2223496e77e6533ef/src/ops.rs#L29-L30

So you should use them!

**Comment by yoanlcq** [comment]
Hi, thanks for bringing this to my attention!

In order to stay compatible with previous versions, I've added "convenience" functions that take a `RangeInclusive` as parameter, and (for better or worse) we still have to live with the functions that use two parameters (one for each bound).

Since I haven't found any obvious issues with that, I'll publish a new version with these additions very soon. I you have any feedback, feel free to let me know!
